modLoader="javafml"
loaderVersion="[1,)"
license="CC BY-NC-SA 4.0"
issueTrackerURL="https://github.com/AZerl0/Ricochet-Enchantment/issues"

[[mods]]
    modId="ricochetenchantment"
    version="1.0.0"
    displayName="Ricochet-Enchantment"
    displayURL="" #optional
    logoFile="pack.png"
    authors="あれい/AZer0"
    credits=""　#optional
    description="Use your ricochet to make trick shots!\n跳弾を使いこなして、トリックショットを決めよう!"

[[dependencies.ricochetenchantment]]
    modId="neoforge"
    mandatory=false
    versionRange="[21.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ricochetenchantment]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22]"
    ordering="NONE"
    side="BOTH"